CREATE SEQUENCE IDN_OAUTH_CONSUMER_APPS_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDN_OAUTH2_SCOPE_SEQUENCE START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDN_SCIM_GROUP_SEQUENCE START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDN_STS_STORE_SEQUENCE START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE SP_APP_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE SP_METADATA_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE SP_INBOUND_AUTH_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE SP_AUTH_STEP_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE SP_CLAIM_DIALECT_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE SP_CLAIM_MAPPING_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE SP_ROLE_MAPPING_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE SP_REQ_PATH_AUTH_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE SP_PROV_CONNECTOR_SEQ START WITH 1 INCREMENT BY 1 NO CACHE

CREATE SEQUENCE SP_AUTH_SCRIPT_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE SP_TEMPLATE_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDN_AUTH_WAIT_STATUS_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDP_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDP_ROLE_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDP_ROLE_MAPPING_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDP_CLAIM_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDP_CLAIM_MAPPING_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDP_AUTHENTICATOR_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDP_METADATA_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDP_AUTHENTICATOR_PROP_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDP_PROVISIONING_CONFIG_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDP_PROV_CONFIG_PROP_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDP_PROV_ENTITY_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDP_LOCAL_CLAIM_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDN_ASSOCIATED_ID_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE WF_WORKFLOW_ASSOCIATION_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDN_PASSWORD_HISTORY_DATA_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDN_CLAIM_DIALECT_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDN_CLAIM_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDN_CLAIM_MAPPED_ATTRIBUTE_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDN_CLAIM_PROPERTY_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDN_CLAIM_MAPPING_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDN_SAML2_ASSERTION_STORE_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDN_SAML2_ARTIFACT_STORE_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDN_OIDC_PROPERTY_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDN_OIDC_REQ_OBJECT_REF_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDN_OIDC_REQ_OBJ_CLAIMS_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDN_OIDC_REQ_OBJ_CLM_VAL_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDN_CERTIFICATE_SEQUENCE START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDN_OIDC_SCOPE_SEQUENCE START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE IDN_OIDC_SCOPE_CLAIM_MAP_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE CM_PII_CATERY_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE CM_PURPOSE_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE CM_PURPOSE_CATERY_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE CM_RECEIPT_SP_ASSOC_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE CM_SP_PURPOSE_ASSOC_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE AM_SUBSCRIBER_SEQUENCE START WITH 1 INCREMENT BY 1

CREATE SEQUENCE AM_APPLICATION_SEQUENCE START WITH 1 INCREMENT BY 1

CREATE SEQUENCE AM_API_SEQUENCE START WITH 1 INCREMENT BY 1

CREATE SEQUENCE AM_API_URL_MAPPING_SEQUENCE START WITH 1 INCREMENT BY 1

CREATE SEQUENCE AM_API_PRODUCT_MAPPING_SEQ START WITH 1 INCREMENT BY 1

CREATE SEQUENCE AM_SUBSCRIPTION_SEQUENCE START WITH 1 INCREMENT BY 1

CREATE SEQUENCE AM_API_RATINGS_SEQUENCE START WITH 1 INCREMENT BY 1

CREATE SEQUENCE AM_TIER_PERMISSIONS_SEQUENCE START WITH 1 INCREMENT BY 1

CREATE SEQUENCE AM_API_LC_EVENT_SEQUENCE START WITH 1 INCREMENT BY 1

CREATE SEQUENCE AM_APP_REGISTRATION_SEQUENCE START WITH 1 INCREMENT BY 1

CREATE SEQUENCE AM_WORKFLOWS_SEQUENCE START WITH 1 INCREMENT BY 1

CREATE SEQUENCE AM_EXTERNAL_STORES_SEQUENCE START WITH 1 INCREMENT BY 1

CREATE SEQUENCE AM_API_DEFAULT_VERSION_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE AM_ALERT_TYPES_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE AM_ALERT_EMAILLIST_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE AM_POLICY_SUBSCRIPTION_seq START WITH 1 INCREMENT BY 1

CREATE SEQUENCE AM_POLICY_APPLICATION_seq START WITH 1 INCREMENT BY 1

CREATE SEQUENCE AM_API_THROTTLE_POLICY_seq START WITH 1 INCREMENT BY 1

CREATE SEQUENCE AM_CONDITION_GROUP_seq START WITH 1 INCREMENT BY 1

CREATE SEQUENCE QUERY_PARAMETER_CONDITION_seq START WITH 1 INCREMENT BY 1

CREATE SEQUENCE QUERY_PARAMETER_CONDITION_seq START WITH 1 INCREMENT BY 1

CREATE SEQUENCE AM_HEADER_FIELD_CONDITION_seq START WITH 1 INCREMENT BY 1

CREATE SEQUENCE AM_JWT_CLAIM_CONDITION_seq START WITH 1 INCREMENT BY 1

CREATE SEQUENCE AM_IP_CONDITION_seq START WITH 1 INCREMENT BY 1

CREATE SEQUENCE AM_POLICY_GLOBAL_seq START WITH 1 INCREMENT BY 1

CREATE SEQUENCE THROTTLE_TIER_PERMISSIONS_seq START WITH 1 INCREMENT BY 1

CREATE SEQUENCE AM_BLOCK_CONDITIONS_seq START WITH 1 INCREMENT BY 1

CREATE SEQUENCE AM_SYSTEM_APPS_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

CREATE SEQUENCE AM_API_LC_PUBLISH_EVENTS_SEQ START WITH 1 INCREMENT BY 1 NO CACHE;

ALTER TABLE IDN_OAUTH_CONSUMER_APPS ADD DEFAULT NEXT VALUE FOR IDN_OAUTH_CONSUMER_APPS_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDN_OAUTH2_SCOPE ADD DEFAULT NEXT VALUE FOR IDN_OAUTH2_SCOPE_SEQUENCE.nextval FOR :NEW.SCOPE_ID;

ALTER TABLE IDN_SCIM_GROUP ADD DEFAULT NEXT VALUE FOR IDN_SCIM_GROUP_SEQUENCE.nextval FOR :NEW.ID;

ALTER TABLE IDN_STS_STORE ADD DEFAULT NEXT VALUE FOR IDN_STS_STORE_SEQUENCE.nextval FOR :NEW.ID;

ALTER TABLE SP_APP ADD DEFAULT NEXT VALUE FOR SP_APP_SEQ.nextval FOR :NEW.ID;

ALTER TABLE SP_METADATA ADD DEFAULT NEXT VALUE FOR SP_METADATA_SEQ.nextval FOR :NEW.ID;

ALTER TABLE SP_INBOUND_AUTH ADD DEFAULT NEXT VALUE FOR SP_INBOUND_AUTH_SEQ.nextval FOR :NEW.ID;

ALTER TABLE SP_AUTH_STEP ADD DEFAULT NEXT VALUE FOR SP_AUTH_STEP_SEQ.nextval FOR :NEW.ID;

ALTER TABLE SP_CLAIM_DIALECT ADD DEFAULT NEXT VALUE FOR SP_CLAIM_DIALECT_SEQ.nextval FOR :NEW.ID;

ALTER TABLE SP_CLAIM_MAPPING ADD DEFAULT NEXT VALUE FOR SP_CLAIM_MAPPING_SEQ.nextval FOR :NEW.ID;

ALTER TABLE SP_ROLE_MAPPING ADD DEFAULT NEXT VALUE FOR SP_ROLE_MAPPING_SEQ.nextval FOR :NEW.ID;

ALTER TABLE SP_REQ_PATH_AUTHENTICATOR ADD DEFAULT NEXT VALUE FOR SP_REQ_PATH_AUTH_SEQ.nextval FOR :NEW.ID;

ALTER TABLE SP_PROVISIONING_CONNECTOR ADD DEFAULT NEXT VALUE FOR SP_PROV_CONNECTOR_SEQ.nextval FOR :NEW.ID;

ALTER TABLE SP_AUTH_SCRIPT ADD DEFAULT NEXT VALUE FOR SP_AUTH_SCRIPT_SEQ.nextval FOR :NEW.ID;

ALTER TABLE SP_TEMPLATE ADD DEFAULT NEXT VALUE FOR SP_TEMPLATE_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDN_AUTH_WAIT_STATUS ADD DEFAULT NEXT VALUE FOR IDN_AUTH_WAIT_STATUS_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDP ADD DEFAULT NEXT VALUE FOR IDP_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDP_ROLE ADD DEFAULT NEXT VALUE FOR IDP_ROLE_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDP_ROLE_MAPPING ADD DEFAULT NEXT VALUE FOR IDP_ROLE_MAPPING_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDP_CLAIM ADD DEFAULT NEXT VALUE FOR IDP_CLAIM_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDP_CLAIM_MAPPING ADD DEFAULT NEXT VALUE FOR IDP_CLAIM_MAPPING_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDP_AUTHENTICATOR ADD DEFAULT NEXT VALUE FOR IDP_AUTHENTICATOR_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDP_METADATA ADD DEFAULT NEXT VALUE FOR IDP_METADATA_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDP_AUTHENTICATOR_PROPERTY ADD DEFAULT NEXT VALUE FOR IDP_AUTHENTICATOR_PROP_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDP_PROVISIONING_CONFIG ADD DEFAULT NEXT VALUE FOR IDP_PROVISIONING_CONFIG_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDP_PROV_CONFIG_PROPERTY ADD DEFAULT NEXT VALUE FOR IDP_PROV_CONFIG_PROP_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDP_PROVISIONING_ENTITY ADD DEFAULT NEXT VALUE FOR IDP_PROV_ENTITY_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDP_LOCAL_CLAIM ADD DEFAULT NEXT VALUE FOR IDP_LOCAL_CLAIM_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDN_ASSOCIATED_ID ADD DEFAULT NEXT VALUE FOR IDN_ASSOCIATED_ID_SEQ.nextval FOR :NEW.ID;

ALTER TABLE WF_WORKFLOW_ASSOCIATION ADD DEFAULT NEXT VALUE FOR WF_WORKFLOW_ASSOCIATION_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDN_PASSWORD_HISTORY_DATA ADD DEFAULT NEXT VALUE FOR IDN_PASSWORD_HISTORY_DATA_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDN_CLAIM_DIALECT ADD DEFAULT NEXT VALUE FOR IDN_CLAIM_DIALECT_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDN_CLAIM ADD DEFAULT NEXT VALUE FOR IDN_CLAIM_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDN_CLAIM_MAPPED_ATTRIBUTE ADD DEFAULT NEXT VALUE FOR IDN_CLAIM_MAPPED_ATTRIBUTE_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDN_CLAIM_PROPERTY ADD DEFAULT NEXT VALUE FOR IDN_CLAIM_PROPERTY_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDN_CLAIM_MAPPING ADD DEFAULT NEXT VALUE FOR IDN_CLAIM_MAPPING_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDN_SAML2_ASSERTION_STORE ADD DEFAULT NEXT VALUE FOR IDN_SAML2_ASSERTION_STORE_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDN_SAML2_ARTIFACT_STORE ADD DEFAULT NEXT VALUE FOR IDN_SAML2_ARTIFACT_STORE_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDN_OIDC_PROPERTY ADD DEFAULT NEXT VALUE FOR IDN_OIDC_PROPERTY_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDN_OIDC_REQ_OBJECT_REFERENCE ADD DEFAULT NEXT VALUE FOR IDN_OIDC_REQ_OBJECT_REF_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDN_OIDC_REQ_OBJECT_CLAIMS ADD DEFAULT NEXT VALUE FOR IDN_OIDC_REQ_OBJ_CLAIMS_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDN_OIDC_REQ_OBJ_CLAIM_VALUES ADD DEFAULT NEXT VALUE FOR IDN_OIDC_REQ_OBJ_CLM_VAL_SEQ.nextval FOR :NEW.ID;

ALTER TABLE IDN_CERTIFICATE ADD DEFAULT NEXT VALUE FOR IDN_CERTIFICATE_SEQUENCE.nextval FOR :NEW.ID;

ALTER TABLE IDN_OIDC_SCOPE ADD DEFAULT NEXT VALUE FOR IDN_OIDC_SCOPE_SEQUENCE.nextval FOR :NEW.ID;

ALTER TABLE IDN_OIDC_SCOPE_CLAIM_MAPPING ADD DEFAULT NEXT VALUE FOR IDN_OIDC_SCOPE_CLAIM_MAP_SEQ.nextval FOR :NEW.ID;

ALTER TABLE CM_PII_CATERY ADD DEFAULT NEXT VALUE FOR CM_PII_CATERY_SEQ.nextval FOR :NEW.ID;

ALTER TABLE CM_PURPOSE ADD DEFAULT NEXT VALUE FOR CM_PURPOSE_SEQ.nextval FOR :NEW.ID;

ALTER TABLE CM_PURPOSE_CATERY ADD DEFAULT NEXT VALUE FOR CM_PURPOSE_CATERY_SEQ.nextval FOR :NEW.ID;

ALTER TABLE CM_RECEIPT_SP_ASSOC ADD DEFAULT NEXT VALUE FOR CM_RECEIPT_SP_ASSOC_SEQ.nextval FOR :NEW.ID;

ALTER TABLE CM_SP_PURPOSE_ASSOC ADD DEFAULT NEXT VALUE FOR CM_SP_PURPOSE_ASSOC_SEQ.nextval FOR :NEW.ID;

ALTER TABLE AM_SUBSCRIBER ADD DEFAULT NEXT VALUE FOR AM_SUBSCRIBER_SEQUENCE.nextval FOR :NEW.SUBSCRIBER_ID;

ALTER TABLE AM_APPLICATION ADD DEFAULT NEXT VALUE FOR AM_APPLICATION_SEQUENCE.nextval FOR :NEW.APPLICATION_ID;

ALTER TABLE AM_API ADD DEFAULT NEXT VALUE FOR AM_API_SEQUENCE.nextval FOR :NEW.API_ID;

ALTER TABLE AM_API_URL_MAPPING ADD DEFAULT NEXT VALUE FOR AM_API_URL_MAPPING_SEQUENCE.nextval FOR :NEW.URL_MAPPING_ID;

ALTER TABLE AM_API_PRODUCT_MAPPING ADD DEFAULT NEXT VALUE FOR AM_API_PRODUCT_MAPPING_SEQ.nextval FOR :NEW.API_PRODUCT_MAPPING_ID;

ALTER TABLE AM_SUBSCRIPTION ADD DEFAULT NEXT VALUE FOR AM_SUBSCRIPTION_SEQUENCE.nextval FOR :NEW.SUBSCRIPTION_ID;

ALTER TABLE AM_API_RATINGS ADD DEFAULT NEXT VALUE FOR AM_API_RATINGS_SEQUENCE.nextval FOR :NEW.RATING_ID;

ALTER TABLE AM_TIER_PERMISSIONS ADD DEFAULT NEXT VALUE FOR AM_TIER_PERMISSIONS_SEQUENCE.nextval FOR :NEW.TIER_PERMISSIONS_ID;

ALTER TABLE AM_API_LC_EVENT ADD DEFAULT NEXT VALUE FOR AM_API_LC_EVENT_SEQUENCE.nextval FOR :NEW.EVENT_ID;

ALTER TABLE AM_APPLICATION_REGISTRATION ADD DEFAULT NEXT VALUE FOR AM_APP_REGISTRATION_SEQUENCE.nextval FOR :NEW.REG_ID;

ALTER TABLE AM_WORKFLOWS ADD DEFAULT NEXT VALUE FOR AM_WORKFLOWS_SEQUENCE.nextval FOR :NEW.WF_ID;

ALTER TABLE AM_EXTERNAL_STORES ADD DEFAULT NEXT VALUE FOR AM_EXTERNAL_STORES_SEQUENCE.nextval FOR :NEW.APISTORE_ID;

ALTER TABLE AM_API_DEFAULT_VERSION ADD DEFAULT NEXT VALUE FOR AM_API_DEFAULT_VERSION_SEQ.nextval FOR :NEW.DEFAULT_VERSION_ID;

ALTER TABLE AM_ALERT_TYPES ADD DEFAULT NEXT VALUE FOR AM_ALERT_TYPES_SEQ.nextval FOR :NEW.ALERT_TYPE_ID;

ALTER TABLE AM_ALERT_EMAILLIST ADD DEFAULT NEXT VALUE FOR AM_ALERT_EMAILLIST_SEQ.nextval FOR :NEW.EMAIL_LIST_ID;

ALTER TABLE AM_POLICY_SUBSCRIPTION ADD DEFAULT NEXT VALUE FOR AM_POLICY_SUBSCRIPTION_seq.NEXTVAL FOR :NEW.POLICY_ID;

ALTER TABLE AM_POLICY_APPLICATION ADD DEFAULT NEXT VALUE FOR AM_POLICY_APPLICATION_seq.NEXTVAL FOR :NEW.POLICY_ID;

ALTER TABLE AM_API_THROTTLE_POLICY ADD DEFAULT NEXT VALUE FOR AM_API_THROTTLE_POLICY_seq.NEXTVAL FOR :NEW.POLICY_ID;

ALTER TABLE AM_CONDITION_GROUP ADD DEFAULT NEXT VALUE FOR AM_CONDITION_GROUP_seq.NEXTVAL FOR :NEW.CONDITION_GROUP_ID;

ALTER TABLE AM_QUERY_PARAMETER_CONDITION ADD DEFAULT NEXT VALUE FOR QUERY_PARAMETER_CONDITION_seq.NEXTVAL FOR :NEW.QUERY_PARAMETER_ID;

ALTER TABLE AM_HEADER_FIELD_CONDITION ADD DEFAULT NEXT VALUE FOR AM_HEADER_FIELD_CONDITION_seq.NEXTVAL FOR :NEW.HEADER_FIELD_ID;

ALTER TABLE AM_JWT_CLAIM_CONDITION ADD DEFAULT NEXT VALUE FOR AM_JWT_CLAIM_CONDITION_seq.NEXTVAL FOR :NEW.JWT_CLAIM_ID;

ALTER TABLE AM_IP_CONDITION ADD DEFAULT NEXT VALUE FOR AM_IP_CONDITION_seq.NEXTVAL FOR :NEW.AM_IP_CONDITION_ID;

ALTER TABLE AM_POLICY_GLOBAL ADD DEFAULT NEXT VALUE FOR AM_POLICY_GLOBAL_seq.NEXTVAL FOR :NEW.POLICY_ID;

ALTER TABLE AM_THROTTLE_TIER_PERMISSIONS ADD DEFAULT NEXT VALUE FOR THROTTLE_TIER_PERMISSIONS_seq.NEXTVAL FOR :NEW.THROTTLE_TIER_PERMISSIONS_ID;

ALTER TABLE AM_BLOCK_CONDITIONS ADD DEFAULT NEXT VALUE FOR AM_BLOCK_CONDITIONS_seq.NEXTVAL FOR :NEW.CONDITION_ID;

ALTER TABLE AM_SYSTEM_APPS ADD DEFAULT NEXT VALUE FOR AM_SYSTEM_APPS_SEQ.nextval FOR :NEW.ID;

ALTER TABLE AM_API_LC_PUBLISH_EVENTS ADD DEFAULT NEXT VALUE FOR AM_API_LC_PUBLISH_EVENTS_SEQ.nextval FOR :NEW.ID;



INSERT INTO IDN_BASE_TABLE values ('WSO2 Identity Server');

INSERT INTO CM_PURPOSE (NAME, DESCRIPTION, PURPOSE_GROUP, GROUP_TYPE, TENANT_ID) VALUES ('DEFAULT', 'For core functionalities of the product', 'DEFAULT', 'SP', '-1234');

INSERT INTO CM_PURPOSE_CATEGORY (NAME, DESCRIPTION, TENANT_ID) VALUES ('DEFAULT','For core functionalities of the product', '-1234');

INSERT INTO AM_ALERT_TYPES (ALERT_TYPE_NAME, STAKE_HOLDER) VALUES ('AbnormalResponseTime', 'publisher');

INSERT INTO AM_ALERT_TYPES (ALERT_TYPE_NAME, STAKE_HOLDER) VALUES ('AbnormalBackendTime', 'publisher');

INSERT INTO AM_ALERT_TYPES (ALERT_TYPE_NAME, STAKE_HOLDER) VALUES ('AbnormalRequestsPerMin', 'subscriber');

INSERT INTO AM_ALERT_TYPES (ALERT_TYPE_NAME, STAKE_HOLDER) VALUES ('AbnormalRequestPattern', 'subscriber');

INSERT INTO AM_ALERT_TYPES (ALERT_TYPE_NAME, STAKE_HOLDER) VALUES ('UnusualIPAccess', 'subscriber');

INSERT INTO AM_ALERT_TYPES (ALERT_TYPE_NAME, STAKE_HOLDER) VALUES ('FrequentTierLimitHitting', 'subscriber');

INSERT INTO AM_ALERT_TYPES (ALERT_TYPE_NAME, STAKE_HOLDER) VALUES ('ApiHealthMonitor', 'publisher');





